### ISSUE TITLE
[ERROR] on open /dev/xdma_control

### ISSUE THREAD

**Issue by orisea** [RC4ML/Shuhai#2]
你好！
我在尝试shuhai例程的时候，到了以下这一步：
sw -> 4. Application Part -> b. Run HBM testing or DDR4 testing with parameters specified in the "config" file (shown in 3.c).
执行以下命令：
$ sudo ./test-hbm --configFile=config.txt
出现了错误：
[ERROR] on open /dev/xdma_control

该路径下没有xdma_control这个文件。
请问问题出在哪里？谢谢！

-----------------------------------------------------------------------------------------------

Hello!

When I try the step: 
sw -> 4. Application Part -> b. Run HBM testing or DDR4 testing with parameters specified in the "config" file (shown in 3.c).
$ sudo ./test-hbm --configFile=config.txt

An error occured:

[ERROR] on open /dev/xdma_ control

There is no such file in this path.
Could you tell me how to solve this problem? Thank you!

**Comment by carlzhang4** [comment]
Maybe you should reboot your machine after loading the bitstream, and don't  forget to use 'sudo insmod xdma_driver.ko'.

**Comment by Phoenix0726** [comment]
> 你好！ 我在尝试shuhai例程的时候，到了以下这一步： sw -> 4. Application Part -> b. Run HBM testing or DDR4 testing with parameters specified in the "config" file (shown in 3.c). 执行以下命令： $ sudo ./test-hbm --configFile=config.txt 出现了错误： [ERROR] on open /dev/xdma_control
> 
> 该路径下没有xdma_control这个文件。 请问问题出在哪里？谢谢！
> 
> Hello!
> 
> When I try the step: sw -> 4. Application Part -> b. Run HBM testing or DDR4 testing with parameters specified in the "config" file (shown in 3.c). $ sudo ./test-hbm --configFile=config.txt
> 
> An error occured:
> 
> [ERROR] on open /dev/xdma_ control
> 
> There is no such file in this path. Could you tell me how to solve this problem? Thank you!

您好，请问您是怎么解决这个问题的？
